apiVersion: apps/v1
kind: Deployment
metadata:
  name: cover-crop
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: cover-crop
  template:
    metadata:
      labels:
        app: cover-crop
    spec:
      containers:
      - image: regdock01.azurecr.io/cover-crop-processor-v2:v1.0.0
        name: cover-crop
        env: 
        - name: RUN_MODE_ENV
          value: "API"  
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: acr-secrets